* Notes
** Information

Author : Ludovic Kuzma
Version : 1.2.2

** Emacs
*** Emacs Builtin keys

<tab> : In c-mode indent the region

C-g : Cancel command

C-/ : Basic text auto complet

M-: : Eval lisp
M-! : Shell command

C-_ : Undo
C-x u : See C-_

C-d : Kill next character
M-d : Kill next word
C-<backspace> : Kill previous word
C-k : Kill next line
M-k : Kill next sentence
C-w : Kill region

C-x C-k : Kill buffer
C-x <right> : Switch to next buffer
C-x <left> : Switch to previous buffer

M-w : Copy region

C-y : Yank (past) last killed text
M-y : Rotate yanked text

M-% : Replace string in region with query
C-M-% : Regex replace string in region with query

C-x C-f : Find file (Open/Create file)
C-x C-d : Find directories (List all direcotries)
C-x C-s : Save current buffer
C-x C-w : Save current buffer in another file

C-a : Beginning of the current line
C-e : End of the current line

M-a : Beginning of the c statement.
M-e : End of the c statement.

C-M-p : Beginning of the current block.
C-M-n : End of the current block.
C-M-u : Parent of the current block.

C-v : Next page
M-v : Previous page

M-< : Beginning of the buffer
M-> : End of the buffer

C-<right> : Beginning of the next word
C-<left> : End of the previous word

C-<up> : Beginning of the sentence
C-<down> : Beginning of the next sentence

C-q <tab> : Insert a tab

C-x r <space> {reg} : Set current position in register {reg}
C-x r j {reg} : Jump to position stored in register {reg}

C-x r s {reg} : Save current region in register {reg}
C-x r i {reg} : Insert text stored in register {reg}

C-s : Search forward
C-r : Search backward
C-M-s : Regex search forward
C-M-r : Regex search backward

C-(s|r) M-s : See C-M-s
C-(s|r) M-r : See C-M-r

C-(s|r) M-c : Toggle case sensitivity
C-(s|r) M-e : Pause to edit search string
C-(s|r) C-w : Append word to search

(C-(s|r)|C-M-(s|r) C-s : Continue search forward
(C-(s|r)|C-M-(s|r) C-r : Continue search backward

C-x 2 : Split the screen horizontaly
C-x 3 : Split the screen verticaly
C-x 1 : Close all screen splits except the current one
C-x 0 : Close the current screen split

C-h f : Describe a function
C-h k : Describe a key

C-x C-c : Quit emacs

*** Org mode keys

<tab> : In org-mode open section

C-c C-t : Mark as TODO, DONE, ...
C-c C-s : Insert schedule
C-c C-d : Insert deadline
C-c C-c : Insert tag

M-<up> : Move past element up
M-<down> : Move past element down

M-<right> : Increase element depth
M-<left> : Decrease element depth

S-<right> : Rotate mark right
S-<left> : Rotate mark left

M-shift RET : To insert a TODO heading

M-O : Open org agenda

*** Helm mode keys

C-x b : List buffers
C-x C-f : Find file (Open/Create file)
C-x C-f C-s : Grep a pattern in the current directory

M-x : List emacs commands
M-m : Open man page

# Helm gtags mode

M-q : List semantic tags
M-s t : List tags
M-s f : List tags in the current function
M-s s : Find symbol

M-s l : Show stack
M-s c : Clear stack

M-. : Find and goto reference and push to stack
M-? : Pop to the previous position

*** Functions args keys

# C and C++ mode

C-: : Complete C/C++ statement

*** Version Control keys

C-x v g : Launch version control interface

# vc-annotate mode

d : Diff of the line revision
l : Log message of the line revision
n : Next revision
p : Previous revision
RET : Open file at the current line

C-x v l : Log message of the current file
C-x v ~ : Open file in a different revision
C-x v = : Diff of the current file

*** Custom keys

<backtab> : Run clang format on the selected region
C-<tab> : Align the current region (see align-current)

C-x C-b : Switch current buffer

M-T : Open todo file
M-N : Open note file

M-<up> : Beginning of the function
M-<down> : Beginning of the next function

M-<left> : Begining of the current block
M-<right> : End of the current block

C-c a : Beginning of the function
C-c e : End of the function
C-c <space> : Select current buffer
C-c c : Comment region
C-c u : Uncomment region
C-c r : Replace string in region
C-c d : Change current directory
C-c s : Delete trailing white space in region
C-c t : Run terminal
C-c k : Kill all buffers with query

*** Emacs commands

Type M-x to browse and run emacs commands

vc-annotate : Launch version control interface
replace-regex : Replace string with regex support
align-regex : Align the current region with regex support

c-set-offset : Display the offset variable used on the current region and
prompt in order to change it, the special symbols used :
- "+" : c-basic-offset +1
- "-" : c-basic-offset -1
- "0" : no offset
- "++" : c-basic-offset +2
- "--" : c-basic-offset -2

** C Coding Style

Kernighan and Ritchie version Stroustrup coding style with some custom configuration
to match Mozzila coding style.
